version: '3.8'

services:
  app:
    container_name: django_publicaciones
    image: alealbaladejo/publicaciones:v1
    restart: always
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=3306
      - DJANGO_SUPERUSER_USERNAME=${ADMIN_USER}
      - DJANGO_SUPERUSER_EMAIL=${ADMIN_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${ADMIN_PASS}
    ports:
      - "${PUERTO_DJ}:8000"
    depends_on:
      - db

  db:
    container_name: mysql_django
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "${PUERTO_DB}:3306"

volumes:
  mariadb_data:
